### ISSUE TITLE
Create a tag for the live tracker

### ISSUE THREAD

**Issue by pwalsh** [okfn/open-budget-survey#66]
We are making changes to the tracker, and I want to keep an easily accessible version of the tracker as currently deployed.

Please add a new git tag called "2015" to https://github.com/okfn/open-budget-survey-tracker based on the last commit before you started working on the codebase.

**Comment by dumyan** [comment]
Commit f52ca7b by Lindsay Ferris that dates from Apr 15 2016 was tagged and pushed upstream.

**Comment by pwalsh** [comment]
thanks
