### ISSUE TITLE
Document hard / soft copy states

### ISSUE THREAD

**Issue by pwalsh** [okfn/open-budget-survey#73]
# Client requests

- We’d want hard/soft copy to also show as orange, but with a different hover over text than the late status (which we’d obviously would supply).

# We require

- An API to know if something is hard or soft copy

**Comment by pwalsh** [comment]
# from client

The data is in Indaba, so Amida may be able to edit the API and make sure it picks it up? I am happy to write to them about this. Let me know whether you instead prefer to do so, letting them know which information we need, as per our email exchange on this point n.3

# actions

@pwalsh

The Indaba API docs  have no indication of a hard/soft field ( nor many other fields: https://swaggerhub.com/api/seanbolak/Indaba/0.1.0 ). 

We've check the API responses and we see two possible related fields:

- "softcopy": true or false
- "scanned": true or false

I also see examples where scanned can be true, AND softcopy can be true.

I'm assuming scanned refers to a hard copy, but then it is weird that both scanned and softcopy could be true.

How should we interpret this data?

## example document object:

```
{ 
    "id": "5344332bd936a70200000001",
    "approved": true,
    "available": true,
    "comments": "Ce document a fait l'objet de nos recherches depuis le mois d'avril 2014. Ce mois de juin, nous avons aussi à travers un courrier adressé le 19 juin 2014, insisté auprès de la Direction Générale du Budget et des Finances (DGBF) pour l'obtention d'une copie du rapport. Pour finir, la Direction a publié ledit rapport sur son site à l'adresse suivante: http://budget.gouv.ci/nw_budgetaire_plus.php?p=9. Cette publication a été faite depuis le 24 Juin 2014. Nous pouvons donc en conclure que ce document est accessible. Notons qu'en plus de ce rapport du premier trimestre 2014, le Rapport de l'exécution du budget au terme du quatrième trimestre de l'année 2013 a été publié à la même date. (Q1 2014 IYR)",
    "country": "Côte d’Ivoire",
    "countryCode": "CI",
    "created_at": "2014-04-08T17:34:35.317Z",
    "date_published": "24 Juin 2014",
    "date_received": "24 Juin 2014",
    "last_modified": "2014-08-21T19:03:41.822Z",
    "location": "Government Office",
    "location_detail": "",
    "scanned": true,
    "softcopy": true,
    "title": "Rapport de l’exécution du Budget au terme du premier trimestre de l’année 2014 (1st Quarter 2014 IYR)",
    "type": "In-Year Report",
    "uploads": [
      {
        "name": "directive_01_2009_CM_UEMOA portant code de transparence.pdf",
        "filename": "5344332bd936a70200000001/directive_01_2009_CM_UEMOA portant code de transparence.pdf"
      }
    ],
    "url": "http://www.budget.gouv.ci",
    "year": 2014
  }
```

**Comment by pwalsh** [comment]
@dumyan from the API architects:

The Old Indaba API, modeled on the existing New Indaba API, is now operational. We have also added the new fifth status for 2017's document questions (i.e. Hard/Soft Copy Only) to both the New and Old APIs.

Please check and validate.

**Comment by dumyan** [comment]
This is good, documents now have the Hard/Soft state.

**Comment by pwalsh** [comment]
We now have hard/soft copy in the API, and any actual implementation using this will be covered in https://github.com/okfn/open-budget-survey/issues/68 so closing this issue.
