### ISSUE TITLE
Can we easily know what countries to show for a given year?

### ISSUE THREAD

**Issue by pwalsh** [okfn/open-budget-survey#75]
# Client requests

- The data that we will be posting on this page will include 102 countries. 27 of those countries were included in the Tracker pilot and so already have pages on this site. This means that 75 countries will need to be added. We’ll need to remove Armenia, Greece, and Palestine. Is this something that will be populated automatically when the page connects to the data, or will we have to provide you with the full lists?

# We need to check

- @dumyan can we know which countries to show for each year - either directly from the countries endpoint, or, via inspection of another endpoint?

**Comment by dumyan** [comment]
Yes we can see which countries were updated by checking the availability object of the country endpoint for now. But I think we should get on hold with this and wait for the API update (or get info before that), because we're not sure will the update follow the Aquarium structure of the data.

**Comment by pwalsh** [comment]
We have an additional API endpoint now, and, in theory, we now have all data. So pls come back to this once you do https://github.com/okfn/open-budget-survey/issues/90

**Comment by pwalsh** [comment]
@dumyan can we close this?

**Comment by dumyan** [comment]
Yes.

**Comment by dumyan** [comment]
Yes.
