### ISSUE TITLE
Final calculator changes

### ISSUE THREAD

**Issue by pwalsh** [okfn/open-budget-survey#81]
# Client request

- A simple table form for the results, as per....

<img width="686" alt="minimal-table" src="https://cloud.githubusercontent.com/assets/791678/18747705/5728f14e-80d7-11e6-9aa3-49b6e31d3112.png">

# Actions

- @dumyan is it possible to easily modify CSS to reduce the printout to a very small table along the lines of the screenshot above? Please consider and give an estimate of effort. I'm concerned that it it too divergent from the current layout, but et me know.
- I also found a bug: on modified, one modifies the "2017" results, yet the generated heading says "2015"

**Comment by dumyan** [comment]
Currently the page is updated with the printing content (some things get hidden and some templates get shown). It won't be time consuming job to hide most of the page and just populate the table. My estimation is 2 hours at max.

About the bug:
The 2017 results are not yet in so the calculator initializes with the 2015 results, hence 'Modified 2015 results' :). I will change this right now.

**Comment by pwalsh** [comment]
@dumyan ok. go for it as an additional print option (so we can then show he client all options.)

**Comment by pwalsh** [comment]
FIXED.
