### ISSUE TITLE
When printing last 7 questions are not correct

### ISSUE THREAD

**Issue by dumyan** [okfn/open-budget-survey#88]
The last 7 questions don't have number as a indicator but a name and that is probably the culprit why they aren't correctly located in the dbs.

**Comment by pwalsh** [comment]
@dumyan this is a concern. is this an issue with the code or the data?

if it is the data, is this an issue with the new API, or was the issue present in the Aquarium API too?

**Comment by dumyan** [comment]
This is in the explorer which doesn't use the new API nor it used Aquarium. It is a problem with the code and I think it is easily solvable, just need to found what have I overlooked when parsing the explorer data (which is very structured and named very unintuitively).

**Comment by pwalsh** [comment]
@dumyan ok, pls fix.
