### ISSUE TITLE
GDrive links correspondence

### ISSUE THREAD

**Issue by dumyan** [okfn/open-budget-survey#91]
Linking GDrive filenames with the API data is not bulletproof. There were some discrepancies such as 'In-Year Report' vs 'In-Year Reports' (plural vs singular) when matching, extra whitespace in some filenames and so on. This is already handled in the code, but now I have found that some countries names are written differently in GDrive then in the tracker and there are possibly other discrepancies that should be found and corrected.

This issue is extension of #84

**Comment by pwalsh** [comment]
@dumyan we could change this by changing the names in the drive itself, right?

If yes, can you produce a list of discrepant names?

**Comment by pwalsh** [comment]
Moved to #94
